// 应用路由路径常量。
//
// 抽取自 src/routes.tsx，使需要 Routes 常量的模块不必 import @/routes
// （后者在模块加载时调用 createBrowserRouter() 创建 router 实例，会触发
// react-router 的 startNavigation 副作用，在 Jest/jsdom 环境下报错）。
//
// 所有需要 Routes 常量的代码应优先从 @/constants/routes import；
// src/routes.tsx 通过 re-export 保持向后兼容。

export enum Routes {
  Root = '/',
  Login = '/login-next',
  Logout = '/logout',
  Home = '/home',
  Datasets = '/datasets',
  DatasetBase = '/dataset',
  Files = '/files',
  Dataset = `${Routes.DatasetBase}/${Routes.Files}`,
  Agent = '/agent',
  AgentTemplates = '/agent-templates',
  Agents = '/agents',
  Explore = '/explore',
  AgentExplore = `${Routes.Agent}/:id/explore`,
  Memories = '/memories',
  Memory = '/memory',
  MemoryMessage = '/memory-message',
  MemorySetting = '/memory-setting',
  AgentList = '/agent-list',
  Searches = '/searches',
  Search = '/search',
  SearchShare = '/search/share',
  Chats = '/chats',
  Chat = '/chat',

  Skills = '/files/skills',
  ProfileSetting = '/profile-setting',
  Profile = '/profile',
  Api = '/api',
  Mcp = '/mcp',
  Team = '/team',
  Plan = '/plan',
  Model = '/model',
  Prompt = '/prompt',
  DataSource = '/data-source',
  DataSourceDetailPage = '/data-source-detail-page',
  ChatChannel = '/chat-channel',
  ProfileMcp = `${Routes.ProfileSetting}${Routes.Mcp}`,
  ProfileTeam = `${Routes.ProfileSetting}${Routes.Team}`,
  ProfilePlan = `${Routes.ProfileSetting}${Routes.Plan}`,
  ProfileModel = `${Routes.ProfileSetting}${Routes.Model}`,
  ProfilePrompt = `${Routes.ProfileSetting}${Routes.Prompt}`,
  ProfileProfile = `${Routes.ProfileSetting}${Routes.Profile}`,
  DatasetTesting = '/retrieval',
  Chunk = '/chunk',
  ChunkResult = `${Routes.Chunk}${Routes.Chunk}`,
  Parsed = '/parsed',
  ParsedResult = `${Routes.Chunk}${Routes.Parsed}`,
  Result = '/result',
  ResultView = `${Routes.Chunk}${Routes.Result}`,
  KnowledgeGraph = '/knowledge-graph',
  AgentLogPage = '/agent-log-page',
  AgentShare = '/agent/share',
  ChatShare = `${Routes.Chats}/share`,
  ChatWidget = `${Routes.Chats}/widget`,
  UserSetting = '/user-setting',
  DataSetOverview = '/logs',
  DataSetSetting = '/configuration',
  DataflowResult = '/dataflow-result',
  Admin = '/admin',
  AdminServices = `${Routes.Admin}/services`,
  AdminUserManagement = `${Routes.Admin}/users`,
  AdminSandboxSettings = `${Routes.Admin}/sandbox-settings`,
  AdminWhitelist = `${Routes.Admin}/whitelist`,
  AdminRoles = `${Routes.Admin}/roles`,
  AdminMonitoring = `${Routes.Admin}/monitoring`,
  // Multi-Harness P2 (US3):Harness 后端配置 Admin 页面。
  AdminHarnessBackends = `${Routes.Admin}/harness-backends`,
  // Multi-Harness P5 (US1/US2/US3):Team/Project/Tenant-binding Admin 页面。
  AdminTeams = `${Routes.Admin}/teams`,
  AdminProjects = `${Routes.Admin}/projects`,
  AdminTenantBindings = `${Routes.Admin}/tenant-bindings`,
  // spec-010 v8 B-6: 首次安装向导页面(不经过 AuthWrapper)。
  Wizard = '/wizard',
}
